use_frameworks!

platform :ios, '10.0'

target 'WebimKeyboard_Example' do
  pod 'WebimKeyboard', :path => '../'
  
  target 'WebimKeyboard_UNIT_Tests' do
    inherit! :search_paths
  end
  
  target 'WebimKeyboard_UI_Tests' do
    inherit! :complete
  end
end
